### ISSUE TITLE
DOM access

### ISSUE THREAD

**Issue by BohdanOther** [HappyFukcer/Drag-and-drop#2]
https://github.com/HappyFukcer/Drag-and-drop/blob/a435d087dc710cc5f1f23c56a24de7e0a303ee4d/js/script.js#L2

https://github.com/HappyFukcer/Drag-and-drop/blob/a435d087dc710cc5f1f23c56a24de7e0a303ee4d/js/script.js#L12

If you want access DOM element by id use `document.getElementById('id')`
It is much faster then `querySelector`

**Comment by Molphar** [comment]
https://github.com/HappyFukcer/Drag-and-drop/blob/7f7e26fdeff098349b30548a2b82df0569aae182/js/script.js#L6-L7

Done!
