### ISSUE TITLE
Cache DOM elements if possible

### ISSUE THREAD

**Issue by BohdanOther** [HappyFukcer/Drag-and-drop#3]
These DOM nodes are searched  every time you click the button, which is time waste.
You can get them on page load and store in separate variables.

https://github.com/HappyFukcer/Drag-and-drop/blob/a435d087dc710cc5f1f23c56a24de7e0a303ee4d/js/script.js#L12

https://github.com/HappyFukcer/Drag-and-drop/blob/a435d087dc710cc5f1f23c56a24de7e0a303ee4d/js/script.js#L19

This DOM node is accessed once, although it's a good practice to still store it to a separate variable

https://github.com/HappyFukcer/Drag-and-drop/blob/a435d087dc710cc5f1f23c56a24de7e0a303ee4d/js/script.js#L2

**Comment by HappyFukcer** [comment]
https://github.com/HappyFukcer/Drag-and-drop/blob/7f7e26fdeff098349b30548a2b82df0569aae182/js/script.js#L1-L3

https://github.com/HappyFukcer/Drag-and-drop/blob/7f7e26fdeff098349b30548a2b82df0569aae182/js/script.js#L6-L8

Done!

**Comment by Molphar** [comment]
https://github.com/HappyFukcer/Drag-and-drop/blob/7f7e26fdeff098349b30548a2b82df0569aae182/js/script.js#L1-L3

https://github.com/HappyFukcer/Drag-and-drop/blob/7f7e26fdeff098349b30548a2b82df0569aae182/js/script.js#L6-L8

Done!
