### ISSUE TITLE
Magic stuff

### ISSUE THREAD

**Issue by BohdanOther** [HappyFukcer/Drag-and-drop#4]
https://github.com/HappyFukcer/Drag-and-drop/blob/a435d087dc710cc5f1f23c56a24de7e0a303ee4d/js/script.js#L84-L85

What `+` in front of `oofset` does?
Use `Number()` constructor to parse numbers, not some js magic behavior

**Comment by Molphar** [comment]
https://github.com/HappyFukcer/Drag-and-drop/blob/7f7e26fdeff098349b30548a2b82df0569aae182/js/script.js#L112-L113

Should I use Number of parseInt?

**Comment by BohdanOther** [comment]
They are different

parseInt tries to parse integer exactly (also there's a parseFloat function)
Also parseInt has additional second parameter for basis.

plus there're some neat differences in parsing logic, see here
https://stackoverflow.com/questions/4090518/what-is-the-difference-between-parseint-and-number


I'd say use `Number` when you know that you're expecting number value hidden in string

Use parseInt when you don't know what to expect
