### ISSUE TITLE
Code style

### ISSUE THREAD

**Issue by BohdanOther** [HappyFukcer/Drag-and-drop#5]
https://github.com/HappyFukcer/Drag-and-drop/blob/a435d087dc710cc5f1f23c56a24de7e0a303ee4d/js/script.js#L36-L42

There's a convention for event handler name
you either name it `handleXXX` or `onXXX`

e.g. `handleMouseMove`, `onMouseMove`

You can choose whichever you like better, but stick to one style
And again, event handlers should be dumb/plain/pure functions that just trigger some other functions, probably passing some arguments 

-----------------------------------
https://github.com/HappyFukcer/Drag-and-drop/blob/a435d087dc710cc5f1f23c56a24de7e0a303ee4d/js/script.js#L45

There's a convention to name bool variables starting with 'is' or 'should'
Also name `active` doesn't tell me much and I have to guess from code.
A way better name would be `isDragging`

-----------------------------------
https://github.com/HappyFukcer/Drag-and-drop/blob/a435d087dc710cc5f1f23c56a24de7e0a303ee4d/js/script.js#L18-L19

You use `let` but these variables are not mutated anywhere. Use `const` 
Also don't use `var` at all if you're using let/const

-----------------------------------
https://github.com/HappyFukcer/Drag-and-drop/blob/a435d087dc710cc5f1f23c56a24de7e0a303ee4d/js/script.js#L21-L22

This is not readable. Always put curly braces around `for` loops. 

----------------------------------
https://github.com/HappyFukcer/Drag-and-drop/blob/a435d087dc710cc5f1f23c56a24de7e0a303ee4d/css/styles.css#L1-L10

always try to use shortcut syntax whenever possible
There're some cases when you should not, but this is not one of those
`margin: 20px auto 0`

**Comment by Molphar** [comment]
https://github.com/HappyFukcer/Drag-and-drop/blob/7f7e26fdeff098349b30548a2b82df0569aae182/js/script.js#L44-L49
Renamed all event handlers.

https://github.com/HappyFukcer/Drag-and-drop/blob/7f7e26fdeff098349b30548a2b82df0569aae182/js/script.js#L52
Renamed bool variable to convention and to understand what it is for.

Should I not use `var` at all or only in functions when i am using `let`/`const` ?

https://github.com/HappyFukcer/Drag-and-drop/blob/7f7e26fdeff098349b30548a2b82df0569aae182/js/script.js#L27-L29
Rewrote loop.

https://github.com/HappyFukcer/Drag-and-drop/blob/7f7e26fdeff098349b30548a2b82df0569aae182/css/styles.css#L5
Rewrote style.

**Comment by BohdanOther** [comment]
If you're using let/const it means that you target ES5 environment, in this case you should not use `var`, also you should use es5 features ideally

Basically, don't mix two approaches

**Comment by BohdanOther** [comment]
Refactor event handler names, see comments to last commit
